### ISSUE TITLE
json files always show up.

### ISSUE THREAD

**Issue by itsmewes** [absszero/LaravelGoto#19]
**Describe the bug**
When using Laravel GoTo on a translation string (eg `__('auth.failed')`) that is referenced in an `auth.php` translation file, the json options are shown, even if they have nothing to do with the translation.

**To Reproduce**
1. Have a mix of `.json` and .php` translations in a project.
2. Run Laravel GoTo on a translations string.
3. See that the correct translation options are shown, but also the generic `{en,fr,it,de,etc}.json` files are shown.

**Expected behavior**
When going to a translation file, only the relevant files are shown.

**Screenshots**
![image](https://github.com/user-attachments/assets/6443c3ee-e61a-4817-a62d-696b03d04a89)

**Additional context**
Nothing extra.

This is a minor annoyance since I really like using the `Open all files above in new window` feature which I can't really do anymore, but can still use it to go to each file, just thought I would ask in case it wasn't a massive thing to work on.

**Comment by absszero** [comment]
When using the Laravel GoTo, it is designed to display all potential sources of translations, including .json files. Because JSON files can contain translations that are relevant to the string being referenced. Even if a specific translation string like __('auth.failed') is defined in a php file, the plugin includes JSON files in its results to ensure that no potential translation sources are overlooked.

I hope this clarifies why JSON files are shown and their significance in the translation process. If there are any further questions, please let us know.

**Comment by itsmewes** [comment]
Thank you for your response. There is no reference at all to anything regarding `auth.failed` in the json files. So are the json options shown "just in case" the user wants to look in there?

**Comment by absszero** [comment]
The plugin only searches for filenames to identify potential translation files and does not inspect the file contents to determine whether they should be listed. 

Therefore, as long as the system finds JSON files, they will be listed, even if they do not contain anything related to `auth.failed`. This is to ensure that all potential translation sources are included.

**Comment by itsmewes** [comment]
Ok cool, thanks for your feedback. Really appreciate it.
