### ISSUE TITLE
It replaces some of LSP-intelephense "go to" 

### ISSUE THREAD

**Issue by zigi05** [absszero/LaravelGoto#23]
Let me start off by saying that the package works great. So this is not actually about the issue but about an effect that is not desirable for me personally.

This is a great feature that I've been looking for. However, after using it for a bit, I noticed that it replaces some of the "go to" that were initially handled by LSP-intelephense in my app. I wish it had settings to enable it only on parts that LSP-intelephense doesn't support.

**Comment by absszero** [comment]
Since LSP-intelephense also utilizes the Hover feature for displaying information, this can sometimes cause conflicts. You can resolve this by disabling the Hover feature in LaravelGoto.

To do so, go to:
Preferences > Package Settings > LaravelGoto > Settings

And add the following configuration:

```json
{
    "show_hover": false
}
```

After making this change, you can use the shortcut `Alt + ;` to trigger the "Goto" command instead.

**Comment by absszero** [comment]
改用 phantom https://chatgpt.com/c/68195808-2694-8004-a089-043c4de33552
